spring:
  profiles:
    include: [center]
  ####### database Config #######
  datasource:
    druid:
      connection-init-sqls: set names utf8mb4
      driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://118.24.153.209:3306/dblog?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: Aa@qq.com
  ####### Redis Config #######
  redis:
    database: 3
    # Redis服务器地址
    host: 118.24.153.209
    # Redis服务器连接端口
    port: 6779
    # Redis服务器连接密码（默认为空）
    password: Aa@qq.com

  ####### redis缓存服务配置 #######
  session:
    store-type: redis

  ####### 自定义配置 #######

  ####### 自定义配置 #######
